CI: add a comment to PR with result of checkpatch

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -35,5 +35,23 @@ jobs:
           cd nuttx
           commits="${{ github.event.pull_request.base.sha }}..HEAD"
           git log --oneline $commits
+
+          # run checkpatch, store result to env. var
           echo "../nuttx/tools/checkpatch.sh -g $commits"
-          ../nuttx/tools/checkpatch.sh -g $commits
+          checkresult=$(../nuttx/tools/checkpatch.sh -g $commits)
+          checkstatus=$?
+          echo "checkresult=$checkresult" >> $GITHUB_ENV
+          echo $checkresult
+
+          # fail or no depending on checkpatch status
+          [ "$checkstatus" = "0" ]
+
+      - name: Add comment to PR
+        uses: actions/github-script@0.3.0
+        if: ${{ failure() && github.event_name == 'pull_request' }}
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
+            github.issues.createComment({ issue_number, owner, repo,
+              body: format('This PR failed the check step. The following problems were found:\n{0}\nFor guidance on NuttX C Coding Standard, follow [this link](https://nuttx.apache.org/docs/latest/contributing/coding_style.html)', env.checkresult) });
